
Vagrant.configure(2) do |config|

  config.vm.box = "modernIE/w7-ie10"

  config.vm.box_check_update = false


  config.vm.synced_folder "syncedFolder/", "C:/RFT_Files/"

  config.vm.communicator = "winrm"
  config.vm.network :forwarded_port, guest: 3389, host: 33389, auto_correct: true
  config.rdp.width  = 1440 # default: 1024
  config.rdp.height = 900  # default: 768

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    # Customize the amount of memory on the VM: Setting it to a better size of 2048MB
    # Also setting cpu cores to 2
    vb.cpus = 2
    vb.memory = "2048"
    vb.name = "Perquimans-sshekha3-AutoBlackTest"
  end

  # Install Chocolatey
  # Install Java, version 1.07 is installed as needed for tool, and other pre-reqs
  config.vm.provision :shell, path: "shellScripts/install_chocolatey.bat"
  config.vm.provision :shell, path: "shellScripts/install_java.bat"
  config.vm.provision :shell, path: "shellScripts/install_clone_git.bat" 
  config.vm.provision :shell, path: "shellScripts/copy_setup.bat" 
  config.vm.provision :shell, path: "shellScripts/install_rft.bat"
  config.vm.provision :shell, inline: "shutdown -r -f"
  config.vm.provision :shell, path: "shellScripts/enable_jre.bat"    
  config.vm.provision :shell, path: "shellScripts/bootstrap.bat" 
  config.vm.provision :shell, inline: "shutdown -r -f"
    
  

end